name: Deploy Shell

on:
  push:
    tags:
      - "shell-v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Pull Env
        run: |
          cd apps/shell
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build
        run: |
          cd apps/shell
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy
        run: |
          cd apps/shell
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}